import { useEffect, useMemo, useRef, useState, type ChangeEvent, type Dispatch, type ReactNode, type SetStateAction } from "react";
import { CaretDown, CaretRight, Check, ClipboardText, FileText, Funnel, List, MagnifyingGlass, Play, SidebarSimple, SplitHorizontal, Stop, UploadSimple, WarningCircle, X } from "@phosphor-icons/react";
import { fullTextForVersion, scenesForVersion, seedEntities, seedImpacts, seedTasks, suggestionsForScene, taxonomyLabel, versionOptions } from "./data";
import { processVersionScenes, type BreakdownSuggestion } from "./lib/aiClient";
import { fallbackFixtureSuggestions, reviewSuggestionCount } from "./lib/fallbackReview";
import { parseLocalScript, TEXT_LIMIT } from "./lib/scriptImport";
import type { EntityRelation, ImportedScene, ProcessingState, ProductionEntity, Scene, SceneProcessing, Suggestion, SuggestionStatus, TaskRow, VersionImpact } from "./types";

type TabId = "review" | "tasks";
type VersionId = "version-v1" | "version-v2" | "local-import";
const statusText: Record<SuggestionStatus, string> = { pending: "待人工处理", created: "已采用为实体", merged: "已关联既有实体", deferred: "已忽略", adopted: "已有实体来源" };
const stateText: Record<ProcessingState, string> = { waiting: "等待处理", queued: "等待", preparing: "准备请求", requesting: "正在请求", review_ready: "DeepSeek 已校验待审", fallback_ready: "fallback 待审", failed: "请求失败", cancelled: "已取消" };
const formalScenes = [...scenesForVersion("version-v1"), ...scenesForVersion("version-v2")];
const sourceName = (id: string, local: Scene[]) => [...formalScenes, ...local].find((scene) => scene.id === id)?.title ?? "历史来源";
const idleProcessing = (scenes: Scene[]) => Object.fromEntries(scenes.map((scene) => [scene.id, { state: "waiting", mode: null, reason: null, suggestionCount: 0 } satisfies SceneProcessing]));

function IconButton({ label, children, onClick }: { label: string; children: ReactNode; onClick?: () => void }) { return <button className="icon-button" type="button" aria-label={label} title={label} onClick={onClick}>{children}</button>; }

function Header({ versionId, onVersionChange, onImport, onSceneToggle, impacts, impactOpen, onImpactToggle, impactDetail }: { versionId: VersionId; onVersionChange: (value: VersionId) => void; onImport: () => void; onSceneToggle: () => void; impacts: VersionImpact[]; impactOpen: boolean; onImpactToggle: () => void; impactDetail: ReactNode }) {
  const pending = impacts.filter((impact) => impact.status === "pending");
  return <header className="topbar"><div className="brand-cluster"><IconButton label="场次列表" onClick={onSceneToggle}><List size={21} /></IconButton><strong className="project-name">剧本生产台</strong><span className="header-divider" /><label className="version-control">当前版本<select aria-label="选择剧本版本" value={versionId} onChange={(event) => onVersionChange(event.target.value as VersionId)}>{versionOptions.map((version) => <option key={version.id} value={version.id}>{version.label}</option>)}{versionId === "local-import" && <option value="local-import">本地导入 · 当前浏览器</option>}</select></label><button className="import-trigger" type="button" onClick={onImport}><UploadSimple size={16} />导入 TXT</button></div><div className="impact-wrap">{versionId === "version-v2" && <button className={`impact-button ${pending.length ? "" : "resolved"}`} type="button" aria-expanded={impactOpen} aria-controls="impact-detail" onClick={onImpactToggle}><WarningCircle size={18} weight="fill" /><span>{pending.length ? `V2 有 ${pending.length} 项关系待审` : "V2 关系已人工处理"}</span><CaretDown className={impactOpen ? "rotate" : ""} size={14} /></button>}{impactOpen && impactDetail}</div><nav className="header-actions" aria-label="演示状态"><span><ClipboardText size={17} />本地审阅</span><span><MagnifyingGlass size={18} />证据定位</span><span><Funnel size={18} />未下发草稿</span></nav></header>;
}

function SceneRail({ scenes, activeId, open, processing, onToggle, onSelect }: { scenes: Scene[]; activeId: string; open: boolean; processing: Record<string, SceneProcessing>; onToggle: () => void; onSelect: (id: string) => void }) {
  return <aside className={`scene-rail ${open ? "" : "collapsed"}`} aria-label="处理单元列表"><div className="panel-heading">{open && <h2>处理单元</h2>}<button className="collapse-control" type="button" aria-expanded={open} aria-controls="scene-list" onClick={onToggle}><SidebarSimple size={19} /><span className="sr-only">{open ? "收起" : "展开"}场次栏</span></button></div>{open && <div id="scene-list" className="scene-list">{scenes.map((scene) => { const item = processing[scene.id]; return <button key={scene.id} type="button" className={`scene-row ${activeId === scene.id ? "active" : ""}`} onClick={() => onSelect(scene.id)}><span className="scene-number">{scene.sampleIndex}</span><span className="scene-copy"><strong>{scene.sourceAct && scene.sourceScene ? `${scene.sourceAct}, ${scene.sourceScene}` : scene.title}</strong><small>{scene.isDemoAdaptation ? "演示制作修订" : scene.title}</small><small className={`process-state ${item?.state ?? "waiting"}`}>{stateText[item?.state ?? "waiting"]}{item?.mode ? ` · ${item.mode === "deepseek" ? "DeepSeek" : `fallback${item.reason ? ` / ${item.reason}` : ""}`}` : ""}{item?.suggestionCount ? ` · ${item.suggestionCount} 条` : ""}</small></span>{item?.state === "requesting" && <span className="update-dot" aria-label="正在请求" />}</button>; })}</div>}</aside>;
}

function EvidenceText({ text, quote, active }: { text: string; quote?: string; active: boolean }) { if (!active || !quote) return <>{text}</>; const index = text.indexOf(quote); if (index < 0) return <>{text}</>; return <>{text.slice(0, index)}<mark className="evidence-focus">{quote}</mark>{text.slice(index + quote.length)}</>; }

function ScriptDocument({ scenes, activeId, evidence }: { scenes: Scene[]; activeId: string; evidence: { sceneId: string; quote: string } | null }) {
  const fullText = scenes[0]?.versionId === "local-import" ? scenes.map((scene) => scene.text).join("\n\n") : fullTextForVersion(scenes[0]?.versionId ?? "");
  return <article className="script-document" aria-labelledby="script-title"><div className="editor-toolbar"><span><FileText size={16} />当前导入版本 · 完整文本</span><small>点击左侧处理单元或右侧证据定位；不替换全文</small></div><div className="script-page" id="script-page"><h1 id="script-title">{scenes[0]?.versionId === "local-import" ? "本地导入版本" : "当前剧本版本完整阅读"}</h1>{scenes.map((scene) => { const displayText = scene.fullTextRange ? fullText.slice(scene.fullTextRange.start, scene.fullTextRange.end) : scene.text; return <section id={`scene-anchor-${scene.id}`} className={`script-scene ${activeId === scene.id ? "active-scene" : ""}`} key={scene.id}><h2>{scene.title}</h2><p className="source-line">{scene.sourceLocator ?? (scene.versionId === "local-import" ? "本地导入 · 未上传" : scene.isDemoAdaptation ? "项目内演示制作修订" : "来源版本文本")}</p><p className="scene-text"><EvidenceText text={displayText} quote={evidence?.sceneId === scene.id ? evidence.quote : undefined} active={evidence?.sceneId === scene.id} /></p></section>; })}<div className="legend"><span><i className="legend-evidence" />来源原文与版本全文</span><span><i className="legend-suggestion" />右侧为可人工处理的建议</span></div></div></article>;
}

function SuggestionCard({ item, entities, open, onToggle, onValueChange, onEvidence, onAction }: { item: Suggestion; entities: ProductionEntity[]; open: boolean; onToggle: () => void; onValueChange: (value: string) => void; onEvidence: () => void; onAction: (action: SuggestionStatus) => void }) {
  const done = item.status !== "pending"; const target = entities.find((entity) => entity.id === item.mergeTargetId); const mode = item.mode === "fixture" ? "预置审阅" : item.mode === "deepseek" ? "DeepSeek 已校验" : `fallback${item.reason ? ` · ${item.reason}` : ""}`;
  return <section className={`suggestion-card ${done ? "resolved" : ""}`}><button className="suggestion-summary" type="button" aria-expanded={open} aria-controls={`suggestion-${item.id}`} onClick={onToggle}><span><b>{item.id}</b><strong>{item.type}</strong><em>{mode}</em></span><span>{done && <small>{statusText[item.status]}</small>}{open ? <CaretDown size={15} /> : <CaretRight size={15} />}</span></button>{open && <div className="suggestion-body" id={`suggestion-${item.id}`}><button className="evidence-link" type="button" onClick={onEvidence}>来源证据：{item.source}</button><label htmlFor={`suggestion-input-${item.id}`}>建议名称<input id={`suggestion-input-${item.id}`} value={item.value} onChange={(event) => onValueChange(event.target.value)} /></label><small className="suggestion-detail">{item.detail}</small>{!done ? <div className="card-actions"><button type="button" onClick={() => onAction("created")}>采用为新实体</button>{target && <button className="primary" type="button" onClick={() => onAction("merged")}>关联「{target.name}」</button>}<button type="button" onClick={() => onAction("deferred")}>忽略</button></div> : <button className="restore-button" type="button" onClick={() => onAction("pending")}>重新处理</button>}</div>}</section>;
}

function ImpactReview({ impacts, entities, onResolve }: { impacts: VersionImpact[]; entities: ProductionEntity[]; onResolve: (id: string, relation: EntityRelation) => void }) { return <div className="impact-popover" id="impact-detail" role="status"><div className="impact-title"><SplitHorizontal size={17} /><strong>V2 场次—实体关系审阅</strong></div>{impacts.map((impact) => <div className="impact-item" key={impact.id}><p>{impact.summary}</p>{impact.status === "pending" ? <div className="impact-actions"><button type="button" onClick={() => onResolve(impact.id, "split")}>补入新场次</button><button type="button" onClick={() => onResolve(impact.id, "kept")}>保留既有关联</button></div> : <p className="impact-result"><Check size={15} />已人工处理：{entities.find((entity) => entity.id === impact.entityId)?.name ?? impact.entityId}</p>}</div>)}</div>; }

function EntityWorkspace({ entities, tasks, localScenes, onGenerateTask, onResolve }: { entities: ProductionEntity[]; tasks: TaskRow[]; localScenes: Scene[]; onGenerateTask: (id: string) => void; onResolve: (entityId: string, relation: EntityRelation) => void }) { return <div className="entity-workspace" role="tabpanel"><div className="ai-notice"><strong>建议均待人工审阅</strong><span>通过“分析全部处理单元”时，浏览器才向同源 <code>/api/ai/breakdown</code> 发送当前单元文本；导入本身只在本地浏览器处理。</span></div><div className="entity-list">{entities.map((entity) => <section className="entity-card" key={entity.id}><div><strong>{entity.name}</strong><span>{entity.kind}</span></div><p>{entity.metadata}</p><small>来源：{entity.sourceSceneIds.map((id) => sourceName(id, localScenes)).join("、")}</small>{entity.relation === "needs-review" && <div className="entity-review"><b>V2 关联待人工处理</b><button type="button" onClick={() => onResolve(entity.id, "split")}>补入新场次</button><button type="button" onClick={() => onResolve(entity.id, "kept")}>保留既有关联</button></div>}{entity.relation !== "needs-review" && entity.relation !== "stable" && <small className="entity-stable">已人工决定：{entity.relation === "split" ? "补入新场次" : "保留既有关联"}</small>}<div className="entity-footer"><span>{entity.taskMaterialReady ? "任务材料草稿已就绪 · 未下发" : "尚未生成任务材料"}</span><button type="button" disabled={entity.taskMaterialReady} onClick={() => onGenerateTask(entity.id)}>{entity.taskMaterialReady ? "已生成" : "生成任务材料"}</button></div></section>)}</div><p className="entity-summary">当前 {entities.length} 个生产实体，{tasks.length} 份任务材料均停留在本地，未向任何部门下发。</p><details className="boundary-note" open><summary>产品边界 / 后续能力</summary><p>反向剧本修改提案、Git 式版本管理、真实任务派发与撤回均不在本次演示范围；当前仅展示可追溯的人工审阅和未下发草稿。</p></details></div>; }

function ReviewPanel({ open, onToggle, activeTab, setActiveTab, suggestions, entities, tasks, localScenes, onSuggestionUpdate, onSuggestionAction, onEvidence, onGenerateTask, onResolve, processing }: { open: boolean; onToggle: () => void; activeTab: TabId; setActiveTab: (tab: TabId) => void; suggestions: Suggestion[]; entities: ProductionEntity[]; tasks: TaskRow[]; localScenes: Scene[]; onSuggestionUpdate: (id: string, value: string) => void; onSuggestionAction: (id: string, action: SuggestionStatus) => void; onEvidence: (item: Suggestion) => void; onGenerateTask: (id: string) => void; onResolve: (entityId: string, relation: EntityRelation) => void; processing: SceneProcessing }) { const [opened, setOpened] = useState<string[]>([]); useEffect(() => setOpened(suggestions.map((item) => item.id)), [suggestions]); return <aside className={`review-panel ${open ? "" : "collapsed"}`} aria-label="建议审阅区"><div className="review-tabs" role="tablist">{open && <><button role="tab" aria-selected={activeTab === "review"} onClick={() => setActiveTab("review")}>建议审阅</button><button role="tab" aria-selected={activeTab === "tasks"} onClick={() => setActiveTab("tasks")}>实体与任务</button></>}<button className="collapse-control" type="button" aria-expanded={open} onClick={onToggle}><SidebarSimple size={19} /><span className="sr-only">收起审阅栏</span></button></div>{open && activeTab === "review" && <div className="review-content" role="tabpanel"><div className="review-meta"><span>{stateText[processing.state]}{processing.mode ? ` · ${processing.mode === "deepseek" ? "DeepSeek" : "fallback"}` : ""}</span><span>{suggestions.length} 条建议</span></div><div className="suggestion-stack">{suggestions.length ? suggestions.map((item) => <SuggestionCard key={item.id} item={item} entities={entities} open={opened.includes(item.id)} onToggle={() => setOpened((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} onValueChange={(value) => onSuggestionUpdate(item.id, value)} onEvidence={() => onEvidence(item)} onAction={(action) => onSuggestionAction(item.id, action)} />) : <div className="tab-empty"><p>{processing.state === "failed" ? "该单元请求失败；没有伪造建议。可检查同源 API 后再次分析。" : "该单元尚无建议。使用上方入口分析全部处理单元。"}</p></div>}</div></div>}{open && activeTab === "tasks" && <EntityWorkspace entities={entities} tasks={tasks} localScenes={localScenes} onGenerateTask={onGenerateTask} onResolve={onResolve} />}</aside>; }

const departmentOptions = ["production", "art", "props", "wardrobe", "costume", "makeup_hair", "sound", "lighting", "vfx", "sfx"];
const reviewStatusOptions: TaskRow["reviewStatus"][] = ["草稿", "待复核", "已确认"];
function TaskLedger({ open, onToggle, tasks, allScenes, setTasks }: { open: boolean; onToggle: () => void; tasks: TaskRow[]; allScenes: Scene[]; setTasks: Dispatch<SetStateAction<TaskRow[]>> }) { const groups = useMemo(() => [...new Set(tasks.map((task) => task.department))], [tasks]); const updateTask = (id: string, patch: Partial<TaskRow>) => setTasks((all) => all.map((task) => task.id === id ? { ...task, ...patch } : task)); return <section className={`task-ledger ${open ? "" : "collapsed"}`} id="task-ledger"><div className="ledger-header"><button className="ledger-toggle" type="button" aria-expanded={open} onClick={onToggle}>{open ? <CaretDown size={16} /> : <CaretRight size={16} />}<strong>部门任务材料草稿（未下发）</strong></button>{open && <><small>可编辑材料内容和成熟度；来源、版本与下发状态为生成快照</small><span className="ledger-spacer" /><span>本地演示</span></>}</div>{open && <div className="ledger-scroll"><table><thead><tr><th>部门 / 材料</th><th>来源处理单元</th><th>制作要求</th><th>优先级</th><th>材料状态</th><th>版本</th><th>下发</th></tr></thead>{groups.map((group) => <tbody key={group}><tr className="group-row"><td colSpan={7}><CaretDown size={14} />{group}（{tasks.filter((task) => task.department === group).length}）</td></tr>{tasks.filter((task) => task.department === group).map((task) => <tr key={task.id}><td><div className="ledger-editor"><select aria-label={`负责部门：${task.task}`} value={task.department} onChange={(event) => updateTask(task.id, { department: event.target.value })}>{departmentOptions.map((department) => <option key={department} value={department}>{department}</option>)}</select><input aria-label={`任务标题：${task.task}`} value={task.task} onChange={(event) => updateTask(task.id, { task: event.target.value })} /></div></td><td><span title="来源由生成快照锁定，不能编辑">{task.sourceSceneIds.map((id) => allScenes.find((scene) => scene.id === id)?.title ?? "历史来源").join("、")}</span></td><td><textarea aria-label={`制作要求：${task.task}`} value={task.content} onChange={(event) => updateTask(task.id, { content: event.target.value })} /></td><td><select className={`priority ${task.priority === "高" ? "high" : ""}`} aria-label={`优先级：${task.task}`} value={task.priority} onChange={(event) => updateTask(task.id, { priority: event.target.value as TaskRow["priority"] })}><option>高</option><option>中</option><option>低</option></select></td><td><select aria-label={`材料审阅状态：${task.task}`} value={task.reviewStatus} onChange={(event) => updateTask(task.id, { reviewStatus: event.target.value as TaskRow["reviewStatus"] })}>{reviewStatusOptions.map((status) => <option key={status}>{status}</option>)}</select></td><td><span title="版本由生成快照锁定，不能编辑">{task.versionLabel}</span></td><td><span title="当前 Demo 不执行真实下发">未下发</span></td></tr>)}</tbody>)}</table>{tasks.length === 0 && <p className="ledger-empty">尚无任务材料。请从稳定实体生成草稿。</p>}</div>}</section>; }

function ImportDialog({ onClose, onImport }: { onClose: () => void; onImport: (scenes: ImportedScene[]) => void }) { const [text, setText] = useState(""), [error, setError] = useState(""); const submit = () => { const result = parseLocalScript(text); if (!result.ok) return setError(result.error); onImport(result.scenes); }; const chooseFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.name.toLowerCase().endsWith(".txt")) return setError("仅支持 UTF-8 .txt 文件；不读取 PDF、DOCX 或 FDX。"); setText(await file.text()); setError(""); }; return <div className="import-backdrop" role="presentation"><section className="import-dialog" role="dialog" aria-modal="true" aria-labelledby="import-title"><button className="dialog-close" type="button" aria-label="关闭导入" onClick={onClose}><X size={18} /></button><h2 id="import-title">导入纯文本</h2><p>导入文本只在当前浏览器切分和展示，不会上传。之后仅当你点击“分析全部处理单元”时，才会把每个处理单元发送到同源 AI 接口。</p><label className="file-picker">选择 .txt 文件<input type="file" accept="text/plain,.txt" onChange={chooseFile} /></label><label>或粘贴文本<textarea value={text} onChange={(event) => { setText(event.target.value); setError(""); }} placeholder="粘贴剧本或场次文本…" /></label><small>{text.length.toLocaleString()} / {TEXT_LIMIT.toLocaleString()} 字符</small>{error && <p className="import-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" type="button" onClick={submit}>在本地导入</button></div></section></div>; }

function taskForEntity(entity: ProductionEntity, versionLabel: string): TaskRow { const department = entity.kind === "视觉特效" ? "vfx" : entity.kind === "声音" ? "sound" : "art"; return { id: `${entity.id}-local-task`, entityId: entity.id, department, task: `准备${entity.name}`, sourceSceneIds: entity.sourceSceneIds, content: `${entity.name}：${entity.metadata}`, priority: entity.kind === "视觉特效" ? "高" : "中", reviewStatus: "草稿", versionLabel }; }
function toSuggestions(scene: Scene, mode: "deepseek" | "fallback", reason: string | undefined, payload: BreakdownSuggestion[]): Suggestion[] { return payload.flatMap((item, suggestionIndex) => item.evidence.map((evidence, evidenceIndex) => ({ id: `${mode}-${scene.id}-${suggestionIndex}-${evidenceIndex}`, type: taxonomyLabel(item.taxonomy), taxonomy: item.taxonomy, source: evidence.quote, sourceRange: evidence.range, value: item.label, detail: evidence.rationale ?? item.description ?? "模型建议已通过结构校验，仍待人工制作判断。", sourceSceneId: scene.id, mergeTargetId: item.proposedEntityId, status: "pending", mode, reason }))); }

export function App() { const [versionId, setVersionId] = useState<VersionId>("version-v1"), [localScenes, setLocalScenes] = useState<Scene[]>([]), [activeSceneId, setActiveSceneId] = useState("version-v1-01"), [showImport, setShowImport] = useState(false), [sceneOpen, setSceneOpen] = useState(() => window.innerWidth > 720), [reviewOpen, setReviewOpen] = useState(true), [ledgerOpen, setLedgerOpen] = useState(true), [activeTab, setActiveTab] = useState<TabId>("review"), [entities, setEntities] = useState(seedEntities), [tasks, setTasks] = useState(seedTasks), [impacts, setImpacts] = useState(seedImpacts), [impactOpen, setImpactOpen] = useState(false), [suggestionMap, setSuggestionMap] = useState<Record<string, Suggestion[]>>(() => Object.fromEntries(formalScenes.map((scene) => [scene.id, suggestionsForScene(scene.id)]))), [processing, setProcessing] = useState<Record<string, SceneProcessing>>(() => idleProcessing(formalScenes)), [evidence, setEvidence] = useState<{ sceneId: string; quote: string } | null>(null), [evidenceError, setEvidenceError] = useState(""), [running, setRunning] = useState(false); const cancelRef = useRef(false);
  const scenes = versionId === "local-import" ? localScenes : scenesForVersion(versionId);
  useEffect(() => { const syncSceneRail = () => setSceneOpen(window.innerWidth > 720); syncSceneRail(); window.addEventListener("resize", syncSceneRail); return () => window.removeEventListener("resize", syncSceneRail); }, []);
  useEffect(() => { if (!scenes.some((scene) => scene.id === activeSceneId)) setActiveSceneId(scenes[0]?.id ?? ""); }, [scenes, activeSceneId]); const activeScene = scenes.find((scene) => scene.id === activeSceneId) ?? scenes[0]; const suggestions = suggestionMap[activeScene?.id ?? ""] ?? []; const activeProcessing = processing[activeScene?.id ?? ""] ?? { state: "waiting", mode: null, reason: null, suggestionCount: 0 };
  const selectScene = (id: string) => { setActiveSceneId(id); setEvidence(null); setEvidenceError(""); requestAnimationFrame(() => document.getElementById(`scene-anchor-${id}`)?.scrollIntoView({ behavior: "smooth", block: "start" })); };
  const selectVersion = (next: VersionId) => { setVersionId(next); const nextScenes = next === "local-import" ? localScenes : scenesForVersion(next); setActiveSceneId(nextScenes[0]?.id ?? ""); setImpactOpen(false); setEvidence(null); setEvidenceError(""); };
  const updateSuggestion = (id: string, value: string) => setSuggestionMap((all) => ({ ...all, [activeScene.id]: (all[activeScene.id] ?? []).map((item) => item.id === id ? { ...item, value } : item) }));
  const applySuggestion = (id: string, action: SuggestionStatus) => { const item = suggestions.find((suggestion) => suggestion.id === id); if (!item) return; if (action === "created") setEntities((all) => [...all, { id: `local-${id}`, name: item.value, kind: item.type, taxonomy: item.taxonomy, metadata: `来自 ${item.taxonomy} 建议 · 需补充 Metadata`, sourceSceneIds: [item.sourceSceneId], relation: "stable", taskMaterialReady: false }]); if (action === "merged" && item.mergeTargetId) setEntities((all) => all.map((entity) => entity.id === item.mergeTargetId ? { ...entity, sourceSceneIds: [...new Set([...entity.sourceSceneIds, item.sourceSceneId])] } : entity)); setSuggestionMap((all) => ({ ...all, [activeScene.id]: (all[activeScene.id] ?? []).map((suggestion) => suggestion.id === id ? { ...suggestion, status: action } : suggestion) })); };
  const resolveImpact = (impactId: string, relation: EntityRelation) => { const impact = impacts.find((item) => item.id === impactId); if (!impact) return; setImpacts((all) => all.map((item) => item.id === impactId ? { ...item, status: relation === "split" ? "merged" : "kept" } : item)); setEntities((all) => all.map((entity) => entity.id === impact.entityId ? { ...entity, relation, sourceSceneIds: relation === "split" ? [...new Set([...entity.sourceSceneIds, impact.sceneId])] : entity.sourceSceneIds } : entity)); };
  const locateEvidence = (item: Suggestion) => { const target = scenes.find((scene) => scene.id === item.sourceSceneId); if (!target || target.text.slice(item.sourceRange.start, item.sourceRange.end) !== item.source) { setEvidenceError("无法在当前版本定位该逐字证据；未进行猜测性高亮。"); return; } setEvidenceError(""); setEvidence({ sceneId: item.sourceSceneId, quote: item.source }); setActiveSceneId(item.sourceSceneId); requestAnimationFrame(() => document.getElementById(`scene-anchor-${item.sourceSceneId}`)?.scrollIntoView({ behavior: "smooth", block: "start" })); };
  const runAnalysis = async () => { if (running || !scenes.length) return; cancelRef.current = false; setRunning(true); setEvidenceError(""); setProcessing(idleProcessing(scenes)); const result = await processVersionScenes({ id: versionId, label: versionId === "local-import" ? "本地导入版本" : versionOptions.find((item) => item.id === versionId)?.label ?? versionId }, scenes.map((scene) => ({ id: scene.id, heading: scene.title, text: scene.text })), entities.map((entity) => ({ id: entity.id, taxonomy: entity.taxonomy as never, canonicalName: entity.name, aliases: [] })), { onProgress: (event) => setProcessing((all) => ({ ...all, [event.sceneId]: { ...(all[event.sceneId] ?? { mode: null, reason: null, suggestionCount: 0 }), state: event.state } })), isCancelled: () => cancelRef.current }); setProcessing((all) => ({ ...all, ...Object.fromEntries(result.records.map((record) => { const isFormalFixtureScene = formalScenes.some((item) => item.id === record.sceneId); return [record.sceneId, { state: record.state, mode: record.mode, reason: record.reason, requestId: record.requestId, suggestionCount: reviewSuggestionCount(record, isFormalFixtureScene, suggestionsForScene(record.sceneId), record.suggestionCount) }]; })) })); setSuggestionMap((all) => ({ ...all, ...Object.fromEntries(result.records.filter((record) => record.state !== "failed").map((record) => { const scene = scenes.find((item) => item.id === record.sceneId)!; const fixtureFallback = fallbackFixtureSuggestions(record, formalScenes.some((item) => item.id === record.sceneId), suggestionsForScene(record.sceneId)); return [record.sceneId, fixtureFallback ?? toSuggestions(scene, record.mode!, record.reason ?? undefined, record.suggestions)]; })) })); setRunning(false); };
  const importScenes = (items: ImportedScene[]) => { const next = items.map((item) => ({ ...item, versionId: "local-import", isDemoAdaptation: false })); setLocalScenes(next); setSuggestionMap((all) => ({ ...all, ...Object.fromEntries(next.map((scene) => [scene.id, []])) })); setProcessing((all) => ({ ...all, ...idleProcessing(next) })); setVersionId("local-import"); setActiveSceneId(next[0].id); setImpactOpen(false); setShowImport(false); };
  if (!activeScene) return null; const allScenes = [...formalScenes, ...localScenes]; const currentVersionLabel = versionId === "local-import" ? "本地导入版本" : versionOptions.find((item) => item.id === versionId)?.label ?? versionId;
  return <div className="app-shell"><Header versionId={versionId} onVersionChange={selectVersion} onImport={() => setShowImport(true)} onSceneToggle={() => setSceneOpen((value) => !value)} impacts={impacts} impactOpen={impactOpen} onImpactToggle={() => setImpactOpen((value) => !value)} impactDetail={<ImpactReview impacts={impacts} entities={entities} onResolve={resolveImpact} />} /><main className={`workspace ${sceneOpen ? "" : "scene-closed"} ${reviewOpen ? "" : "review-closed"} ${ledgerOpen ? "" : "ledger-closed"}`}><SceneRail scenes={scenes} activeId={activeScene.id} open={sceneOpen} processing={processing} onToggle={() => setSceneOpen((value) => !value)} onSelect={selectScene} /><section className="document-region"><div className="analysis-bar"><div><strong>{currentVersionLabel}</strong><span>完整剧本常驻阅读 · 共 {scenes.length} 个处理单元</span></div><div>{running ? <button type="button" className="cancel-analysis" onClick={() => { cancelRef.current = true; }}> <Stop size={15} />处理完当前单元后取消</button> : <button type="button" className="run-analysis" onClick={runAnalysis}><Play size={15} weight="fill" />使用 DeepSeek 分析全部处理单元</button>}</div></div>{evidenceError && <p className="evidence-error" role="alert">{evidenceError}</p>}<ScriptDocument scenes={scenes} activeId={activeScene.id} evidence={evidence} /></section><ReviewPanel open={reviewOpen} onToggle={() => setReviewOpen((value) => !value)} activeTab={activeTab} setActiveTab={setActiveTab} suggestions={suggestions} entities={entities} tasks={tasks} localScenes={localScenes} processing={activeProcessing} onSuggestionUpdate={updateSuggestion} onSuggestionAction={applySuggestion} onEvidence={locateEvidence} onGenerateTask={(id) => { const entity = entities.find((item) => item.id === id); if (entity && !entity.taskMaterialReady) { setEntities((all) => all.map((item) => item.id === id ? { ...item, taskMaterialReady: true } : item)); setTasks((all) => [...all, taskForEntity(entity, currentVersionLabel)]); } }} onResolve={(entityId, relation) => { const impact = impacts.find((item) => item.entityId === entityId && item.status === "pending"); if (impact) resolveImpact(impact.id, relation); }} /><TaskLedger open={ledgerOpen} onToggle={() => setLedgerOpen((value) => !value)} tasks={tasks} allScenes={allScenes} setTasks={setTasks} /></main>{showImport && <ImportDialog onClose={() => setShowImport(false)} onImport={importScenes} />}<div className="sr-only" aria-live="polite">{running ? "正在顺序处理剧本单元" : `当前处理单元：${activeScene.title}`}</div></div>;
}
