import { useEffect, useMemo, useState, type ChangeEvent, type Dispatch, type ReactNode, type SetStateAction } from "react";
import { CaretDown, CaretRight, Check, ClipboardText, FileText, Funnel, List, MagnifyingGlass, SidebarSimple, SplitHorizontal, UploadSimple, WarningCircle, X } from "@phosphor-icons/react";
import { scenesForVersion, seedEntities, seedImpacts, seedTasks, suggestionsForScene, taxonomyLabel, versionOptions } from "./data";
import { parseLocalScript, TEXT_LIMIT } from "./lib/scriptImport";
import type { EntityRelation, ImportedScene, ProductionEntity, Scene, Suggestion, SuggestionStatus, TaskRow, VersionImpact } from "./types";

type TabId = "review" | "tasks";
type VersionId = "version-v1" | "version-v2" | "local-import";
const statusText: Record<SuggestionStatus, string> = { pending: "待人工处理", created: "已采用为实体", merged: "已关联既有实体", deferred: "已忽略", adopted: "已有实体来源" };
const formalScenes = [...scenesForVersion("version-v1"), ...scenesForVersion("version-v2")];
const sourceName = (id: string, local: Scene[]) => [...formalScenes, ...local].find((scene) => scene.id === id)?.title ?? "已移除来源";

function IconButton({ label, children, onClick }: { label: string; children: ReactNode; onClick?: () => void }) { return <button className="icon-button" type="button" aria-label={label} title={label} onClick={onClick}>{children}</button>; }

function Header({ versionId, onVersionChange, onImport, impacts, impactOpen, onImpactToggle, impactDetail }: { versionId: VersionId; onVersionChange: (value: VersionId) => void; onImport: () => void; impacts: VersionImpact[]; impactOpen: boolean; onImpactToggle: () => void; impactDetail: ReactNode }) {
  const pending = impacts.filter((impact) => impact.status === "pending");
  return <header className="topbar"><div className="brand-cluster"><IconButton label="场次列表"><List size={21} /></IconButton><strong className="project-name">《暴风雨》</strong><span className="header-divider" /><label className="version-control">剧本版本<select aria-label="选择剧本版本" value={versionId} onChange={(event) => onVersionChange(event.target.value as VersionId)}>{versionOptions.map((version) => <option key={version.id} value={version.id}>{version.id === "version-v1" ? "V1 · 公版节选" : "V2 · 演示制作修订"}</option>)}{versionId === "local-import" && <option value="local-import">本地导入 · 未上传</option>}</select></label><button className="import-trigger" type="button" onClick={onImport}><UploadSimple size={16} />导入文本</button></div><div className="impact-wrap">{versionId === "version-v2" && <button className={`impact-button ${pending.length ? "" : "resolved"}`} type="button" aria-expanded={impactOpen} aria-controls="impact-detail" onClick={onImpactToggle}><WarningCircle size={19} weight="fill" /><span>{pending.length ? `V2 有 ${pending.length} 项关系待审` : "V2 关系已人工处理"}</span><CaretDown className={impactOpen ? "rotate" : ""} size={14} /></button>}{impactOpen && impactDetail}</div><nav className="header-actions" aria-label="项目工具"><span><ClipboardText size={17} />本地 Demo</span><span><MagnifyingGlass size={18} />来源可追溯</span><span><Funnel size={18} />人工审阅</span></nav></header>;
}

function SceneRail({ scenes, activeId, open, onToggle, onSelect }: { scenes: Scene[]; activeId: string; open: boolean; onToggle: () => void; onSelect: (id: string) => void }) { return <aside className={`scene-rail ${open ? "" : "collapsed"}`} aria-label="场次列表"><div className="panel-heading">{open && <h2>场次与来源</h2>}<div className="heading-actions"><button className="collapse-control" type="button" aria-expanded={open} aria-controls="scene-list" onClick={onToggle}><SidebarSimple size={19} /><span className="sr-only">{open ? "收起" : "展开"}场次栏</span></button></div></div>{open && <div id="scene-list" className="scene-list">{scenes.map((scene) => <button key={scene.id} type="button" className={`scene-row ${activeId === scene.id ? "active" : ""}`} onClick={() => onSelect(scene.id)}><span className="scene-number">{scene.sampleIndex}</span><span className="scene-copy"><strong>{scene.sourceAct && scene.sourceScene ? `${scene.sourceAct}, ${scene.sourceScene}` : scene.title}</strong><small>{scene.isDemoAdaptation ? "演示制作修订" : scene.title}</small></span>{scene.isDemoAdaptation && <span className="update-dot" aria-label="演示制作修订" />}</button>)}</div>}</aside>; }

function ScriptDocument({ scene }: { scene: Scene }) { const local = scene.versionId === "local-import"; return <article className="script-document" aria-labelledby="script-title"><div className="editor-toolbar"><span><FileText size={16} />来源文本</span><i /><small>{local ? "本地纯文本 · 未上传、未调用模型" : scene.isDemoAdaptation ? "项目内演示制作修订，不是 Shakespeare 原文" : "MIT Shakespeare 公版英文节选 + 项目自译中文"}</small></div><div className="script-page"><h1 id="script-title">{scene.title}</h1><p className="source-line">{scene.sourceUrl ? <a href={scene.sourceUrl} target="_blank" rel="noreferrer">MIT Shakespeare 来源定位</a> : scene.isDemoAdaptation ? "项目内演示制作修订 · 基于公版原作" : "本地模式：仅保存在当前浏览器，未上传"}{scene.sourceLocator ? ` · ${scene.sourceLocator}` : ""}</p>{scene.englishExcerpt && <section className="source-block"><h2>英文公版片段</h2><pre>{scene.englishExcerpt}</pre></section>}<section className="source-block"><h2>{local ? "本地导入文本" : scene.isDemoAdaptation ? "演示性制作文本" : "简体中文对照（项目自译）"}</h2>{scene.text.split("\n\n").map((paragraph, index) => <p key={index}>{paragraph}</p>)}</section><div className="legend"><span><i className="legend-evidence" />{local ? "仅本地可见" : "来源原文 / 自译对照"}</span><span><i className="legend-suggestion" />右侧为待人工处理的规范建议</span></div></div></article>; }

function SuggestionCard({ item, entities, open, onToggle, onValueChange, onAction }: { item: Suggestion; entities: ProductionEntity[]; open: boolean; onToggle: () => void; onValueChange: (value: string) => void; onAction: (action: SuggestionStatus) => void }) { const done = item.status !== "pending"; const target = entities.find((entity) => entity.id === item.mergeTargetId); return <section className={`suggestion-card ${done ? "resolved" : ""}`}><button className="suggestion-summary" type="button" aria-expanded={open} aria-controls={`suggestion-${item.id}`} onClick={onToggle}><span><b>{item.id}</b><strong>{item.type}</strong><em>确定性建议</em></span><span>{done && <small>{statusText[item.status]}</small>}{open ? <CaretDown size={15} /> : <CaretRight size={15} />}</span></button>{open && <div className="suggestion-body" id={`suggestion-${item.id}`}><p><b>来源锚点：</b>{item.source}</p><label htmlFor={`suggestion-input-${item.id}`}>建议名称<input id={`suggestion-input-${item.id}`} value={item.value} onChange={(event) => onValueChange(event.target.value)} /></label><small className="suggestion-detail">{item.detail}</small>{!done ? <div className="card-actions"><button type="button" onClick={() => onAction("created")}>采用为新实体</button>{target && <button className="primary" type="button" onClick={() => onAction("merged")}>关联「{target.name}」</button>}<button type="button" onClick={() => onAction("deferred")}>忽略</button></div> : <button className="restore-button" type="button" onClick={() => onAction("pending")}>重新处理</button>}</div>}</section>; }

function ImpactReview({ impacts, entities, onResolve }: { impacts: VersionImpact[]; entities: ProductionEntity[]; onResolve: (id: string, relation: EntityRelation) => void }) { return <div className="impact-popover" id="impact-detail" role="status"><div className="impact-title"><SplitHorizontal size={17} /><strong>V2 场次—实体关系审阅</strong></div>{impacts.map((impact) => <div className="impact-item" key={impact.id}><p>{impact.summary}</p>{impact.status === "pending" ? <div className="impact-actions"><button type="button" onClick={() => onResolve(impact.id, "split")}>补入新场次</button><button type="button" onClick={() => onResolve(impact.id, "kept")}>保留既有关联</button></div> : <p className="impact-result"><Check size={15} />已人工处理：{entities.find((entity) => entity.id === impact.entityId)?.name ?? impact.entityId}</p>}</div>)}</div>; }

function EntityWorkspace({ entities, tasks, localScenes, onGenerateTask, onResolve }: { entities: ProductionEntity[]; tasks: TaskRow[]; localScenes: Scene[]; onGenerateTask: (id: string) => void; onResolve: (entityId: string, relation: EntityRelation) => void }) { return <div className="entity-workspace" role="tabpanel"><div className="ai-notice"><strong>确定性 Demo 数据 · 未调用模型</strong><span>保留 <code>/api/ai/breakdown</code> 接口入口；当前界面不接 DeepSeek。</span></div><div className="entity-list">{entities.map((entity) => <section className="entity-card" key={entity.id}><div><strong>{entity.name}</strong><span>{entity.kind}</span></div><p>{entity.metadata}</p><small>来源：{entity.sourceSceneIds.map((id) => sourceName(id, localScenes)).join("、")}</small>{entity.relation === "needs-review" && <div className="entity-review"><b>V2 关联待人工处理</b><button type="button" onClick={() => onResolve(entity.id, "split")}>补入新场次</button><button type="button" onClick={() => onResolve(entity.id, "kept")}>保留既有关联</button></div>}{entity.relation !== "needs-review" && entity.relation !== "stable" && <small className="entity-stable">已人工决定：{entity.relation === "split" ? "补入新场次" : "保留既有关联"}</small>}<div className="entity-footer"><span>{entity.taskMaterialReady ? "任务材料草稿已就绪 · 未下发" : "尚未生成任务材料"}</span><button type="button" disabled={entity.taskMaterialReady} onClick={() => onGenerateTask(entity.id)}>{entity.taskMaterialReady ? "已生成" : "生成任务材料"}</button></div></section>)}</div><p className="entity-summary">当前 {entities.length} 个生产实体，{tasks.length} 份任务材料均停留在本地，未向任何部门下发。</p></div>; }

function ReviewPanel({ open, onToggle, activeTab, setActiveTab, suggestions, entities, tasks, localMode, localScenes, onSuggestionUpdate, onSuggestionAction, onGenerateTask, onResolve }: { open: boolean; onToggle: () => void; activeTab: TabId; setActiveTab: (tab: TabId) => void; suggestions: Suggestion[]; entities: ProductionEntity[]; tasks: TaskRow[]; localMode: boolean; localScenes: Scene[]; onSuggestionUpdate: (id: string, value: string) => void; onSuggestionAction: (id: string, action: SuggestionStatus) => void; onGenerateTask: (id: string) => void; onResolve: (entityId: string, relation: EntityRelation) => void }) { const [opened, setOpened] = useState<string[]>([]); useEffect(() => setOpened(suggestions.map((item) => item.id)), [suggestions]); return <aside className={`review-panel ${open ? "" : "collapsed"}`} aria-label="建议审阅区"><div className="review-tabs" role="tablist">{open && <><button role="tab" aria-selected={activeTab === "review"} onClick={() => setActiveTab("review")}>建议审阅</button><button role="tab" aria-selected={activeTab === "tasks"} onClick={() => setActiveTab("tasks")}>实体与任务</button></>}<button className="collapse-control" type="button" aria-expanded={open} onClick={onToggle}><SidebarSimple size={19} /></button></div>{open && activeTab === "review" && <div className="review-content" role="tabpanel"><div className="review-meta"><span>{localMode ? "本地模式 · 尚未生成建议" : `确定性建议（${suggestions.filter((item) => item.status === "pending").length} 待处理）`}</span><span>来源可定位</span></div>{localMode ? <div className="tab-empty"><p>文本已留在当前浏览器。MVP 不上传文件，也不对导入文本自动调用模型。</p></div> : <div className="suggestion-stack">{suggestions.map((item) => <SuggestionCard key={item.id} item={item} entities={entities} open={opened.includes(item.id)} onToggle={() => setOpened((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} onValueChange={(value) => onSuggestionUpdate(item.id, value)} onAction={(action) => onSuggestionAction(item.id, action)} />)}</div>}</div>}{open && activeTab === "tasks" && <EntityWorkspace entities={entities} tasks={tasks} localScenes={localScenes} onGenerateTask={onGenerateTask} onResolve={onResolve} />}</aside>; }

function TaskLedger({ open, onToggle, tasks, allScenes, setTasks }: { open: boolean; onToggle: () => void; tasks: TaskRow[]; allScenes: Scene[]; setTasks: Dispatch<SetStateAction<TaskRow[]>> }) { const groups = useMemo(() => [...new Set(tasks.map((task) => task.department))], [tasks]); return <section className={`task-ledger ${open ? "" : "collapsed"}`} id="task-ledger"><div className="ledger-header"><button className="ledger-toggle" type="button" aria-expanded={open} onClick={onToggle}>{open ? <CaretDown size={16} /> : <CaretRight size={16} />}<strong>部门任务材料草稿（未下发）</strong></button>{open && <><small>生成时冻结版本和来源摘要；不通知部门主管</small><span className="ledger-spacer" /><span>本地演示</span></>}</div>{open && <div className="ledger-scroll"><table><thead><tr><th>部门 / 材料</th><th>来源场次</th><th>制作要求</th><th>优先级</th><th>状态</th><th>版本</th><th>下发</th></tr></thead>{groups.map((group) => <tbody key={group}><tr className="group-row"><td colSpan={7}><CaretDown size={14} />{group}（{tasks.filter((task) => task.department === group).length}）</td></tr>{tasks.filter((task) => task.department === group).map((task) => <tr key={task.id}><td><input type="checkbox" checked={task.done} aria-label={`完成任务：${task.task}`} onChange={() => setTasks((all) => all.map((row) => row.id === task.id ? { ...row, done: !row.done } : row))} /><span className={task.done ? "done" : ""}>{task.task}</span></td><td>{task.sourceSceneIds.map((id) => allScenes.find((scene) => scene.id === id)?.title ?? "历史来源").join("、")}</td><td>{task.content}</td><td className={`priority ${task.priority === "高" ? "high" : ""}`}>{task.priority}</td><td>{task.done ? "已完成" : "草稿"}</td><td>{task.versionLabel}</td><td>未下发</td></tr>)}</tbody>)}</table>{tasks.length === 0 && <p className="ledger-empty">尚无任务材料。请从稳定实体生成草稿。</p>}</div>}</section>; }

function ImportDialog({ onClose, onImport }: { onClose: () => void; onImport: (scenes: ImportedScene[]) => void }) { const [text, setText] = useState(""), [error, setError] = useState(""); const submit = () => { const result = parseLocalScript(text); if (!result.ok) return setError(result.error); onImport(result.scenes); }; const chooseFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!file.name.toLowerCase().endsWith(".txt")) return setError("仅支持 UTF-8 .txt 文件；不读取 PDF、DOCX 或 FDX。"); setText(await file.text()); setError(""); }; return <div className="import-backdrop" role="presentation"><section className="import-dialog" role="dialog" aria-modal="true" aria-labelledby="import-title"><button className="dialog-close" type="button" aria-label="关闭导入" onClick={onClose}><X size={18} /></button><h2 id="import-title">导入纯文本</h2><p>文件只在当前浏览器读取，不会上传。支持粘贴文本或 UTF-8 <code>.txt</code>，上限 {TEXT_LIMIT.toLocaleString()} 字符。</p><label className="file-picker">选择 .txt 文件<input type="file" accept="text/plain,.txt" onChange={chooseFile} /></label><label>或粘贴文本<textarea value={text} onChange={(event) => { setText(event.target.value); setError(""); }} placeholder="粘贴剧本或场次文本…" /></label><small>{text.length.toLocaleString()} / {TEXT_LIMIT.toLocaleString()} 字符</small>{error && <p className="import-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" type="button" onClick={submit}>在本地导入</button></div></section></div>; }

function taskForEntity(entity: ProductionEntity): TaskRow { const department = entity.kind === "视觉特效" ? "vfx" : entity.kind === "声音" ? "sound" : "art"; return { id: `${entity.id}-local-task`, entityId: entity.id, department, task: `准备${entity.name}`, sourceSceneIds: entity.sourceSceneIds, content: `${entity.name}：${entity.metadata}`, priority: entity.kind === "视觉特效" ? "高" : "中", done: false, versionLabel: "当前本地工作区" }; }

export function App() { const [versionId, setVersionId] = useState<VersionId>("version-v1"), [localScenes, setLocalScenes] = useState<Scene[]>([]), [activeSceneId, setActiveSceneId] = useState("version-v1-01"), [showImport, setShowImport] = useState(false), [sceneOpen, setSceneOpen] = useState(() => window.innerWidth > 720), [reviewOpen, setReviewOpen] = useState(true), [ledgerOpen, setLedgerOpen] = useState(true), [activeTab, setActiveTab] = useState<TabId>("review"), [entities, setEntities] = useState(seedEntities), [tasks, setTasks] = useState(seedTasks), [impacts, setImpacts] = useState(seedImpacts), [impactOpen, setImpactOpen] = useState(false), [suggestionEdits, setSuggestionEdits] = useState<Record<string, string>>({}), [suggestionStatuses, setSuggestionStatuses] = useState<Record<string, SuggestionStatus>>({});
  const scenes = versionId === "local-import" ? localScenes : scenesForVersion(versionId); useEffect(() => { if (!scenes.some((scene) => scene.id === activeSceneId)) setActiveSceneId(scenes[0]?.id ?? ""); }, [scenes, activeSceneId]); const activeScene = scenes.find((scene) => scene.id === activeSceneId) ?? scenes[0]; const rawSuggestions = activeScene && versionId !== "local-import" ? suggestionsForScene(activeScene.id) : []; const suggestions = rawSuggestions.map((item) => ({ ...item, value: suggestionEdits[item.id] ?? item.value, status: suggestionStatuses[item.id] ?? item.status }));
  const selectVersion = (next: VersionId) => { setVersionId(next); const nextScenes = next === "local-import" ? localScenes : scenesForVersion(next); setActiveSceneId(nextScenes[0]?.id ?? ""); setImpactOpen(false); };
  const applySuggestion = (id: string, action: SuggestionStatus) => { const item = suggestions.find((suggestion) => suggestion.id === id); if (!item) return; if (action === "created") setEntities((all) => [...all, { id: `local-${id}`, name: item.value, kind: item.type, metadata: `来自 ${item.taxonomy} 建议 · 需补充 Metadata`, sourceSceneIds: [item.sourceSceneId], relation: "stable", taskMaterialReady: false }]); if (action === "merged" && item.mergeTargetId) setEntities((all) => all.map((entity) => entity.id === item.mergeTargetId ? { ...entity, sourceSceneIds: [...new Set([...entity.sourceSceneIds, item.sourceSceneId])] } : entity)); setSuggestionStatuses((all) => ({ ...all, [id]: action })); };
  const resolveImpact = (impactId: string, relation: EntityRelation) => { const impact = impacts.find((item) => item.id === impactId); if (!impact) return; setImpacts((all) => all.map((item) => item.id === impactId ? { ...item, status: relation === "split" ? "merged" : "kept" } : item)); setEntities((all) => all.map((entity) => entity.id === impact.entityId ? { ...entity, relation, sourceSceneIds: relation === "split" ? [...new Set([...entity.sourceSceneIds, impact.sceneId])] : entity.sourceSceneIds } : entity)); };
  const resolveEntity = (entityId: string, relation: EntityRelation) => { const impact = impacts.find((item) => item.entityId === entityId && item.status === "pending"); if (impact) resolveImpact(impact.id, relation); };
  const importScenes = (items: ImportedScene[]) => { const next = items.map((item) => ({ ...item, versionId: "local-import", isDemoAdaptation: false })); setLocalScenes(next); setVersionId("local-import"); setActiveSceneId(next[0].id); setImpactOpen(false); setShowImport(false); };
  if (!activeScene) return null;
  const allScenes = [...formalScenes, ...localScenes];
  return <div className="app-shell"><Header versionId={versionId} onVersionChange={selectVersion} onImport={() => setShowImport(true)} impacts={impacts} impactOpen={impactOpen} onImpactToggle={() => setImpactOpen((value) => !value)} impactDetail={<ImpactReview impacts={impacts} entities={entities} onResolve={resolveImpact} />} /><main className={`workspace ${sceneOpen ? "" : "scene-closed"} ${reviewOpen ? "" : "review-closed"} ${ledgerOpen ? "" : "ledger-closed"}`}><SceneRail scenes={scenes} activeId={activeScene.id} open={sceneOpen} onToggle={() => setSceneOpen((value) => !value)} onSelect={setActiveSceneId} /><ScriptDocument scene={activeScene} /><ReviewPanel open={reviewOpen} onToggle={() => setReviewOpen((value) => !value)} activeTab={activeTab} setActiveTab={setActiveTab} suggestions={suggestions} entities={entities} tasks={tasks} localMode={versionId === "local-import"} localScenes={localScenes} onSuggestionUpdate={(id, value) => setSuggestionEdits((all) => ({ ...all, [id]: value }))} onSuggestionAction={applySuggestion} onGenerateTask={(id) => { const entity = entities.find((item) => item.id === id); if (entity && !entity.taskMaterialReady) { setEntities((all) => all.map((item) => item.id === id ? { ...item, taskMaterialReady: true } : item)); setTasks((all) => [...all, taskForEntity(entity)]); } }} onResolve={resolveEntity} /><TaskLedger open={ledgerOpen} onToggle={() => setLedgerOpen((value) => !value)} tasks={tasks} allScenes={allScenes} setTasks={setTasks} /></main>{showImport && <ImportDialog onClose={() => setShowImport(false)} onImport={importScenes} />}<div className="sr-only" aria-live="polite">当前版本：{versionId}</div></div>; }
