import { useMemo, useState, type ReactNode } from "react";
import { ArrowClockwise, ArrowCounterClockwise, BookmarkSimple, CaretDown, CaretRight, Check, ClipboardText, DownloadSimple, Funnel, List, MagnifyingGlass, Plus, Rows, SidebarSimple, SplitHorizontal, WarningCircle } from "@phosphor-icons/react";
import { scenes, seedEntities, seedSuggestions, seedTasks } from "./data";
import type { EntityKind, ProductionEntity, Suggestion, SuggestionStatus, TaskRow } from "./types";

type TabId = "review" | "tasks";
const statusText: Record<SuggestionStatus, string> = { pending: "待处理", created: "已创建实体", merged: "已合并", deferred: "暂不处理" };
const sourceLabel = (sampleIndex: number) => scenes.find((scene) => scene.sampleIndex === sampleIndex)?.productionLabel ?? `样本第 ${sampleIndex} 项`;
const sourceLabels = (sampleIndices: number[]) => sampleIndices.map(sourceLabel).join("、");

function IconButton({ label, children, onClick, disabled = false }: { label: string; children: ReactNode; onClick?: () => void; disabled?: boolean }) {
  return <button className="icon-button" type="button" aria-label={label} title={label} onClick={onClick} disabled={disabled}>{children}</button>;
}

function Header({ impactOpen, onImpactToggle, impactResolved, impactDetail }: { impactOpen: boolean; onImpactToggle: () => void; impactResolved: boolean; impactDetail: ReactNode }) {
  const text = impactResolved ? "V2 场次关联已人工处理" : "V2 有 1 项关联待人工处理";
  return <header className="topbar"><div className="brand-cluster"><IconButton label="打开主菜单" disabled><List size={21} /></IconButton><strong className="project-name">雾港</strong><span className="header-divider" /><button className="select-button" type="button" disabled>剧本 V2 <CaretDown size={14} /></button><span className="header-divider" /><button className="select-button demo-select" type="button" disabled>演示数据 <CaretDown size={14} /></button></div><div className="impact-wrap"><button className={`impact-button ${impactResolved ? "resolved" : ""}`} type="button" aria-expanded={impactOpen} aria-controls="impact-detail" onClick={onImpactToggle}><WarningCircle size={19} weight="fill" /><span>{text}</span><CaretDown className={impactOpen ? "rotate" : ""} size={14} /></button>{impactOpen && impactDetail}</div><nav className="header-actions" aria-label="项目工具"><button type="button" disabled><ClipboardText size={18} />版本对比</button><button type="button" disabled><BookmarkSimple size={18} />书签</button><IconButton label="搜索" disabled><MagnifyingGlass size={20} /></IconButton><IconButton label="筛选" disabled><Funnel size={20} /></IconButton></nav></header>;
}

function SceneRail({ open, onToggle }: { open: boolean; onToggle: () => void }) {
  const [active, setActive] = useState(13);
  return <aside className={`scene-rail ${open ? "" : "collapsed"}`} aria-label="场次列表"><div className="panel-heading">{open && <h2>场次</h2>}<div className="heading-actions">{open && <IconButton label="新建场次" disabled><Plus size={18} /></IconButton>}<button className="collapse-control" type="button" aria-expanded={open} aria-controls="scene-list" onClick={onToggle}><SidebarSimple size={19} /><span className="sr-only">{open ? "收起" : "展开"}场次栏</span></button></div></div>{open && <div id="scene-list" className="scene-list">{scenes.map((scene) => <button key={scene.id} type="button" className={`scene-row ${active === scene.id ? "active" : ""}`} onClick={() => setActive(scene.id)}><span className="scene-number">{scene.id}</span><span className="scene-copy"><strong>{scene.title}</strong><small>{scene.version}</small></span><span className="update-dot" aria-label={scene.updated ? "已更新" : undefined} /></button>)}</div>}</aside>;
}

function ScriptDocument() {
  return <article className="script-document" aria-labelledby="script-title"><div className="editor-toolbar" aria-label="文本工具栏"><button type="button" disabled>正文 <CaretDown size={13} /></button><i /><button type="button" aria-label="撤销" disabled><ArrowCounterClockwise size={16} /></button><button type="button" aria-label="重做" disabled><ArrowClockwise size={16} /></button><i /><button type="button" aria-label="粗体" disabled><b>B</b></button><button type="button" aria-label="斜体" disabled><em>I</em></button><button type="button" aria-label="项目符号" disabled><Rows size={16} /></button><small>字数：826</small></div><div className="script-page"><h1 id="script-title">第 13 场&nbsp;&nbsp;内景 · 旧仓库 · 夜</h1><p>夜&nbsp;&nbsp;|&nbsp;&nbsp;旧仓库内部</p><p>仓库内部昏暗。高大的空间里回荡着水滴落下的声音。</p><p>镜头缓缓推进，右侧是一扇 <mark className="evidence">锈蚀的卷帘门</mark>，门缝下透出一线冷风。</p><p>左侧墙上，一盏 <mark className="inference">红色应急灯闪烁</mark>，将货架的影子拉得忽长忽短。</p><p>远处，隐约传来 <mark className="suggestion">货轮汽笛</mark> 的声音，由远及近，又被风声带走。</p><p>地面有积水，倒映着灯光的碎影。</p><div className="dialogue"><strong>阿凯</strong><span>（压低声音）</span><p>他应该就在这附近。</p></div><p>阿凯沿着货架间的通道小心前行，手电光束扫过散落的木箱和铁桶。</p><div className="dialogue"><strong>小七</strong><p>这里雾气太重了，信号时有时无。</p></div><p>阿凯停下脚步，竖起耳朵倾听，远处的汽笛声再次响起。</p><div className="legend"><span><i className="legend-evidence" />场次原文（来源证据）</span><span><i className="legend-suggestion" />模拟 AI 建议</span></div></div></article>;
}

function SuggestionCard({ item, entities, open, onToggle, onValueChange, onAction }: { item: Suggestion; entities: ProductionEntity[]; open: boolean; onToggle: () => void; onValueChange: (value: string) => void; onAction: (action: SuggestionStatus) => void }) {
  const done = item.status !== "pending";
  return <section className={`suggestion-card ${done ? "resolved" : ""}`}><button className="suggestion-summary" type="button" aria-expanded={open} aria-controls={`suggestion-${item.id}`} onClick={onToggle}><span><b>{item.id}</b><strong>{item.type}</strong><em>模拟 AI</em></span><span>{done && <small>{statusText[item.status]}</small>}{open ? <CaretDown size={15} /> : <CaretRight size={15} />}</span></button>{open && <div className="suggestion-body" id={`suggestion-${item.id}`}><p><b>来源摘要：</b>{item.source}</p><label htmlFor={`suggestion-input-${item.id}`}>建议内容<input id={`suggestion-input-${item.id}`} name={`suggestion-${item.id}`} value={item.value} onChange={(event) => onValueChange(event.target.value)} /></label><small className="suggestion-detail">{item.detail}</small>{!done ? <div className="card-actions"><button type="button" onClick={() => onAction("created")}>创建实体</button><button className="primary" type="button" onClick={() => onAction("merged")}>合并到「{entities.find((entity) => entity.id === item.mergeTargetId)?.name ?? "既有实体"}」</button><button type="button" onClick={() => onAction("deferred")}>暂不处理</button></div> : <button className="restore-button" type="button" onClick={() => onAction("pending")}>重新处理</button>}</div>}</section>;
}

function ImpactReview({ resolved, onResolve }: { resolved: boolean; onResolve: (mode: "split" | "keep") => void }) {
  return <div className="impact-popover" id="impact-detail" role="status"><div className="impact-title"><SplitHorizontal size={17} /><strong>样本序列插入影响审阅</strong></div><p>V2 在样本第 2 项后插入第 3 项，原第 3 项顺延为第 4 项。实体「货轮汽笛」关联了样本第 2、4 项，需人工决定是否补入新来源。</p>{resolved ? <p className="impact-result"><Check size={15} />已人工处理：实体关联已更新为当前 V2 方案。</p> : <div className="impact-actions"><button type="button" onClick={() => onResolve("split")}>补入新样本项</button><button type="button" onClick={() => onResolve("keep")}>保留既有关联</button></div>}</div>;
}

function EntityWorkspace({ entities, tasks, onGenerateTask, onResolve }: { entities: ProductionEntity[]; tasks: TaskRow[]; onGenerateTask: (id: string) => void; onResolve: (mode: "split" | "keep") => void }) {
  return <div className="entity-workspace" role="tabpanel"><div className="ai-notice"><strong>模拟 AI · 本地 seed</strong><span>预留 <code>/api/ai/breakdown</code>，当前未调用</span></div><div className="entity-list">{entities.map((entity) => <section className="entity-card" key={entity.id}><div><strong>{entity.name}</strong><span>{entity.kind}</span></div><p>{entity.metadata}</p><small>样本来源：{sourceLabels(entity.sourceSampleIndices)}</small>{entity.relation === "needs-review" && <div className="entity-review"><b>V2 样本关联待人工处理</b><button type="button" onClick={() => onResolve("split")}>补入新样本项</button><button type="button" onClick={() => onResolve("keep")}>保留关联</button></div>}{entity.relation === "split" && <small className="entity-stable">已补入样本第 3 项来源</small>}{entity.relation === "kept" && <small className="entity-stable">已保留原有样本关联</small>}<div className="entity-footer"><span>{entity.taskMaterialReady ? "任务材料已生成 · 未真实下发" : "尚未生成任务材料"}</span><button type="button" disabled={entity.taskMaterialReady} onClick={() => onGenerateTask(entity.id)}>{entity.taskMaterialReady ? "已生成" : "生成任务材料"}</button></div></section>)}</div><p className="entity-summary">当前 {entities.length} 个稳定生产实体，{tasks.length} 份任务草稿均停留在本地，未向任何部门下发。</p></div>;
}

function ReviewPanel({ open, onToggle, activeTab, setActiveTab, suggestions, entities, tasks, onSuggestionUpdate, onSuggestionAction, onGenerateTask, onResolve }: { open: boolean; onToggle: () => void; activeTab: TabId; setActiveTab: (tab: TabId) => void; suggestions: Suggestion[]; entities: ProductionEntity[]; tasks: TaskRow[]; onSuggestionUpdate: (id: number, value: string) => void; onSuggestionAction: (id: number, action: SuggestionStatus) => void; onGenerateTask: (id: string) => void; onResolve: (mode: "split" | "keep") => void }) {
  const [opened, setOpened] = useState<number[]>([1, 2, 3]); const pending = suggestions.filter((suggestion) => suggestion.status === "pending").length;
  return <aside className={`review-panel ${open ? "" : "collapsed"}`} aria-label="建议审阅区"><div className="review-tabs" role="tablist" aria-label="右侧工作区">{open && <><button role="tab" aria-selected={activeTab === "review"} onClick={() => setActiveTab("review")}>建议审阅</button><button role="tab" aria-selected={activeTab === "tasks"} onClick={() => setActiveTab("tasks")}>实体与任务</button></>}<button className="collapse-control" type="button" aria-expanded={open} onClick={onToggle}><SidebarSimple size={19} /><span className="sr-only">{open ? "收起" : "展开"}审阅栏</span></button></div>{open && activeTab === "review" && <div className="review-content" role="tabpanel"><div className="review-meta"><span>模拟 AI 建议（{pending} 待处理）</span><span>{sourceLabel(2)} 证据</span></div><div className="suggestion-stack">{suggestions.map((item) => <SuggestionCard key={item.id} item={item} entities={entities} open={opened.includes(item.id)} onToggle={() => setOpened((ids) => ids.includes(item.id) ? ids.filter((id) => id !== item.id) : [...ids, item.id])} onValueChange={(value) => onSuggestionUpdate(item.id, value)} onAction={(action) => onSuggestionAction(item.id, action)} />)}</div></div>}{open && activeTab === "tasks" && <EntityWorkspace entities={entities} tasks={tasks} onGenerateTask={onGenerateTask} onResolve={onResolve} />}</aside>;
}

function TaskLedger({ open, onToggle, tasks, setTasks }: { open: boolean; onToggle: () => void; tasks: TaskRow[]; setTasks: React.Dispatch<React.SetStateAction<TaskRow[]>> }) {
  const groups = useMemo(() => [...new Set(tasks.map((task) => task.department))], [tasks]);
  return <section className={`task-ledger ${open ? "" : "collapsed"}`} id="task-ledger" aria-labelledby="ledger-title"><div className="ledger-header"><button className="ledger-toggle" type="button" aria-expanded={open} aria-controls="ledger-table" onClick={onToggle}>{open ? <CaretDown size={16} /> : <CaretRight size={16} />}<strong id="ledger-title">任务材料草稿（未真实下发）</strong></button>{open && <><small>由稳定生产实体生成；仅本地演示，不会通知部门主管</small><span className="ledger-spacer" /><button type="button" disabled>全部场次 <CaretDown size={13} /></button><button type="button" disabled><DownloadSimple size={16} />导出台账</button></>}</div>{open && <div className="ledger-scroll" id="ledger-table"><table><thead><tr><th>部门 / 材料</th><th>来源样本</th><th>任务内容</th><th>优先级</th><th>状态</th><th>责任人</th><th>下发</th></tr></thead>{groups.map((group) => <tbody key={group}><tr className="group-row"><td colSpan={7}><CaretDown size={14} />{group}（{tasks.filter((task) => task.department === group).length}）</td></tr>{tasks.filter((task) => task.department === group).map((task) => <tr key={task.id}><td><input type="checkbox" checked={task.done} aria-label={`完成任务：${task.task}`} onChange={() => setTasks((all) => all.map((row) => row.id === task.id ? { ...row, done: !row.done } : row))} /><span className={task.done ? "done" : ""}>{task.task}</span></td><td>{sourceLabels(task.sourceSampleIndices)}</td><td>{task.content}</td><td className={`priority ${task.priority === "高" ? "high" : ""}`}>{task.priority}</td><td>{task.done ? "已完成" : "草稿"}</td><td>待分配</td><td>未下发</td></tr>)}</tbody>)}</table>{tasks.length === 0 && <p className="ledger-empty">尚无任务材料。请在“实体与任务”中从稳定实体生成草稿。</p>}</div>}</section>;
}

function taskForEntity(entity: ProductionEntity): TaskRow {
  const setup: Record<EntityKind, Pick<TaskRow, "department" | "task" | "priority">> = { 场景: { department: "美术组", task: "场景搭建", priority: "高" }, 道具: { department: "美术组", task: "道具准备", priority: "中" }, 视觉特效: { department: "声音组", task: "环境音设计", priority: "中" } };
  const item = setup[entity.kind];
  return { id: `${entity.id}-task`, entityId: entity.id, ...item, sourceSampleIndices: entity.sourceSampleIndices, content: `${entity.name}，${entity.metadata}`, done: false };
}

export function App() {
  const [impactOpen, setImpactOpen] = useState(false), [sceneOpen, setSceneOpen] = useState(() => window.innerWidth > 720), [reviewOpen, setReviewOpen] = useState(true), [ledgerOpen, setLedgerOpen] = useState(true), [activeTab, setActiveTab] = useState<TabId>("review"), [suggestions, setSuggestions] = useState(seedSuggestions), [entities, setEntities] = useState(seedEntities), [tasks, setTasks] = useState(seedTasks);
  const impactResolved = entities.find((entity) => entity.id === "sound")?.relation !== "needs-review";
  const updateSuggestion = (id: number, value: string) => setSuggestions((items) => items.map((item) => item.id === id ? { ...item, value } : item));
  const applySuggestion = (id: number, action: SuggestionStatus) => {
    const item = suggestions.find((suggestion) => suggestion.id === id); if (!item) return;
    if (action === "created") setEntities((all) => [...all, { id: `suggestion-${id}`, name: item.value, kind: item.type, metadata: `来自模拟 AI · ${item.type}`, sourceSampleIndices: [item.sourceSampleIndex], relation: "stable", taskMaterialReady: false }]);
    if (action === "merged") setEntities((all) => all.map((entity) => entity.id === item.mergeTargetId ? { ...entity, sourceSampleIndices: [...new Set([...entity.sourceSampleIndices, item.sourceSampleIndex])] } : entity));
    setSuggestions((items) => items.map((suggestion) => suggestion.id === id ? { ...suggestion, status: action } : suggestion));
  };
  const generateTask = (id: string) => { const entity = entities.find((item) => item.id === id); if (!entity || entity.taskMaterialReady) return; setEntities((all) => all.map((item) => item.id === id ? { ...item, taskMaterialReady: true } : item)); setTasks((all) => [...all, taskForEntity(entity)]); };
  const resolveImpact = (mode: "split" | "keep") => setEntities((all) => all.map((entity) => entity.id === "sound" ? { ...entity, relation: mode === "split" ? "split" : "kept", sourceSampleIndices: mode === "split" ? [2, 3, 4] : entity.sourceSampleIndices } : entity));
  return <div className="app-shell"><Header impactOpen={impactOpen} onImpactToggle={() => setImpactOpen((value) => !value)} impactResolved={impactResolved} impactDetail={<ImpactReview resolved={impactResolved} onResolve={resolveImpact} />} /><main className={`workspace ${sceneOpen ? "" : "scene-closed"} ${reviewOpen ? "" : "review-closed"} ${ledgerOpen ? "" : "ledger-closed"}`}><SceneRail open={sceneOpen} onToggle={() => setSceneOpen((value) => !value)} /><ScriptDocument /><ReviewPanel open={reviewOpen} onToggle={() => setReviewOpen((value) => !value)} activeTab={activeTab} setActiveTab={setActiveTab} suggestions={suggestions} entities={entities} tasks={tasks} onSuggestionUpdate={updateSuggestion} onSuggestionAction={applySuggestion} onGenerateTask={generateTask} onResolve={resolveImpact} /><TaskLedger open={ledgerOpen} onToggle={() => setLedgerOpen((value) => !value)} tasks={tasks} setTasks={setTasks} /></main><div className="sr-only" aria-live="polite">当前还有 {suggestions.filter((item) => item.status === "pending").length} 条模拟 AI 建议待处理</div></div>;
}
